name: "Publish To OSS"

on:
  push:
    branches: [ master ]

jobs:
  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    steps:
      # 1. 声明 checkout 仓库代码到工作区
      - name: Checkout
        uses: actions/checkout@v2.4.0

      # 2. 安装 Java JDK 环境
      - name: Setup Java JDK
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'zulu'
          java-version: 8

      # 3. 发布到Maven中央仓库
      - name: Publish To OSS
        uses: samuelmeuli/action-maven-publish@v1.4.0
        with:
          server_id: ossrh
          nexus_username: ${{ secrets.OSSRH_USER }}
          nexus_password: ${{ secrets.OSSRH_PASSWORD }}
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
          maven_goals_phases: clean deploy -e
